name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{secrets.BRANDLIBEL_ME_HOST}}
        username: ubuntu
        privateKey: ${{secrets.BRANDLIBEL_ME_PEM}}
        command: sudo /brandlibel-me/deploy.sh
