name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
      with:
        node-version: 10
    - run: yarn install
    - run: yarn test
    - name: Build and run production
      run: yarn prod
